spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initialization-mode: always
        password: ''
        platform: mysql
        url: jdbc:mysql://localhost:3306/mydb
        username: root
    jaxb:
        enabled: true
    jpa:
        hibernate:
            show-sql: true
server:
    port : 8080

info:
    app:
        name: CarWash Service
        description: Blah, blah , blah
        version: 1.0.0
tokinho:
    secret: 9ED52ADA317C43338FF710C6D6491BC4

springdoc:
    swagger-ui:
        path: /swagger-ui.html