spring:
    profiles:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initialization-mode: always
        password: ''
        platform: mysql
        url: jdbc:mysql://192.17.85.123:3306/mydb
        username: root
    jaxb:
        enabled: true
    jpa:
        hibernate:
            show-sql: true
server:
    port : 8090

info:
    app:
        name: CarWash Service
        description: Blah, blah , blah
        version: 1.0.0
